name: auth
description: A starting point for Dart libraries or applications.
version: 0.1.0
author: long1eu <lung.razvan@gmail.com>

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  root:
    path: ../root
  rxdart: ^0.22.6

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.9.4
