name: app_platform
description: A starting point for Dart libraries or applications.
version: 0.0.1
homepage: https://www.example.com
author: long1eu <lung.razvan@gmail.com>

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  root:
    path: ../root

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.9.4
