name: root
description: A starting point for Dart libraries or applications.
version: 0.1.0
author: long1eu <lung.razvan@gmail.com>

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  path: ^1.6.4
  built_value: ^6.8.2
  built_collection: 4.2.2
  redux: ^3.0.0
  redux_logging: ^0.3.0
  redux_epics: ^0.11.0
  rxdart: ^0.22.6
  http: ^0.12.0+2
  hive:
    git: https://github.com/long1eu/hive

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.9.4
  build_runner: ^1.7.0
  built_value_generator: ^6.8.2
  hive_generator:
    git: https://github.com/long1eu/hive_generator
